[package]
name = "slugify-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.20"
regex = "1.10"
unicode-normalization = "0.1"
deunicode = "1.1"
html-escape = "0.2"
unicode-segmentation = "1"
