[alias]
coverage = "llvm-cov --package slugify-rs --html --ignore-filename-regex '/usr/src|/rustc-|src/bin/.*' --open"
coverage-lcov = "llvm-cov --package slugify-rs --lcov --output-path lcov.info --ignore-filename-regex '/usr/src|/rustc-|src/bin/.*'"

[target.aarch64-apple-darwin]
rustflags = [
	"-C", "link-arg=-undefined",
	"-C", "link-arg=dynamic_lookup",
]
# If you cross-compile locally with osxcross you may need to set a linker
# linker = "o64-clang"
