name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-slugify-rs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create virtualenv and install maturin and test dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          # Ensure coverage backend is installed so pytest-cov can write XML
          pip install maturin pytest pytest-cov coverage

      - name: Run Rust unit tests (slugify-rs crate only)
        run: |
          cargo test -p slugify-rs --lib

      - name: Build and install Python extension for tests
        run: |
          . .venv/bin/activate
          .venv/bin/maturin develop --release --features python

      - name: Run Python tests with coverage
        run: |
          . .venv/bin/activate
          # Generate coverage XML at repository root as coverage.xml
          pytest tests/python --cov=src --cov-report=xml:coverage.xml

      - name: Show coverage artifact for debugging
        run: |
          . .venv/bin/activate
          echo "Current working directory: $(pwd)"
          ls -la
          if [ -f coverage.xml ]; then
            echo "coverage.xml found:"; head -n 40 coverage.xml
          else
            echo "coverage.xml NOT found"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: false
          # If your repo requires a Codecov token (private/protected branches),
          # set the secret `CODECOV_TOKEN` and uncomment the next line:
          # token: ${{ secrets.CODECOV_TOKEN }}
