name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-slugify-rs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install maturin and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin pytest pytest-cov

      - name: Run Rust unit tests (slugify-rs crate only)
        run: |
          cargo test -p slugify-rs --lib

      - name: Build and install Python extension for tests
        run: |
          maturin develop --release --features python

      - name: Run Python tests with coverage
        run: |
          pytest tests/python --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
