name: Publish PyPI (OIDC)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install maturin
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install maturin

      - name: Publish via OIDC (Trusted Publisher)
        env:
          PYPI_USERNAME: __token__
        run: |
          . .venv/bin/activate
          # maturin supports using the PyPI token from the environment;
          # with OIDC as a trusted publisher, the PyPI project will allow
          # the GitHub Actions job to publish without storing a long-lived token here.
          .venv/bin/maturin publish --no-sdist --manylinux off
